{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-build",
    "version": "0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "dwed36xq7jef7lqgidung2kjcu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "conclave-build-0.4-SNAPSHOT.jar",
          "url": "conclave-build-0.4-SNAPSHOT.jar",
          "size": 1014,
          "sha512": "da2d2dd5187570a6cf84eda0c4b2e1ccf160679e9b5a0d6a02c79c3896e6d87bbad7851b2d4943e6b56e6448496c9571ddeb353261155bd2e99e0709c4fe7784",
          "sha256": "2d7d4d6617af3c02cb91a2bcc7964e450430a4b376077974ad4b0e5c74f2e4f5",
          "sha1": "10351ca20df95fc75d49e85976bc748c57d3ff7f",
          "md5": "8e0136c5cbc39a664e137e2f56ad46cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "conclave-build-0.4-SNAPSHOT.jar",
          "url": "conclave-build-0.4-SNAPSHOT.jar",
          "size": 1014,
          "sha512": "da2d2dd5187570a6cf84eda0c4b2e1ccf160679e9b5a0d6a02c79c3896e6d87bbad7851b2d4943e6b56e6448496c9571ddeb353261155bd2e99e0709c4fe7784",
          "sha256": "2d7d4d6617af3c02cb91a2bcc7964e450430a4b376077974ad4b0e5c74f2e4f5",
          "sha1": "10351ca20df95fc75d49e85976bc748c57d3ff7f",
          "md5": "8e0136c5cbc39a664e137e2f56ad46cd"
        }
      ]
    }
  ]
}
